### ISSUE TITLE
Allow Preflight 01: box model

### ISSUE THREAD

**Issue by marcioendo** [objectos/objectos#394]
## CSS

```css
*,
::before,
::after {
  box-sizing: border-box; /* 1 */
  border-width: 0; /* 2 */
  border-style: solid; /* 2 */
  border-color: theme('borderColor.DEFAULT', currentColor); /* 2 */
}
```

## Tasks

- [x] UniversalSelector
- [x] PseudoElementSelector
- [x] ListSelector
