### ISSUE TITLE
Allow Preflight 03: margin

### ISSUE THREAD

**Issue by marcioendo** [objectos/objectos#396]
## CSS

```css
/*
1. Remove the margin in all browsers.
2. Inherit line-height from `html` so users can set them as a class directly on the `html` element.
*/

body {
  margin: 0; /* 1 */
  line-height: inherit; /* 2 */
}
```
