### ISSUE TITLE
Allow Preflight 04: hr

### ISSUE THREAD

**Issue by marcioendo** [objectos/objectos#397]
## CSS

```css
/*
1. Add the correct height in Firefox.
2. Correct the inheritance of border color in Firefox. (https://bugzilla.mozilla.org/show_bug.cgi?id=190655)
3. Ensure horizontal rules are visible by default.
*/

hr {
  height: 0; /* 1 */
  color: inherit; /* 2 */
  border-top-width: 1px; /* 3 */
}
```
