### ISSUE TITLE
Allow Preflight 05: heading

### ISSUE THREAD

**Issue by marcioendo** [objectos/objectos#398]
## CSS

```css
/*
Remove the default font size and weight for headings.
*/

h1,
h2,
h3,
h4,
h5,
h6 {
  font-size: inherit;
  font-weight: inherit;
}
```
