### ISSUE TITLE
Allow Preflight 06: anchor

### ISSUE THREAD

**Issue by marcioendo** [objectos/objectos#399]
## CSS

```css
/*
Reset links to optimize for opt-in styling instead of opt-out.
*/

a {
  color: inherit;
  text-decoration: inherit;
}
```
