### ISSUE TITLE
Allow Preflight 07: strong

### ISSUE THREAD

**Issue by marcioendo** [objectos/objectos#401]
## CSS

```css
/*
Add the correct font weight in Edge and Safari.
*/

b,
strong {
  font-weight: bolder;
}
```
