### ISSUE TITLE
Allow Preflight 08: pre/code

### ISSUE THREAD

**Issue by marcioendo** [objectos/objectos#402]
## CSS

```css
code,
kbd,
samp,
pre {
  font-family: theme('fontFamily.mono', ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace); /* 1 */
  font-size: 1em; /* 2 */
}
```
