### ISSUE TITLE
Allow Preflight 09: small

### ISSUE THREAD

**Issue by marcioendo** [objectos/objectos#403]
## CSS

```css
/*
Add the correct font size in all browsers.
*/

small {
  font-size: 80%;
}
```
