### ISSUE TITLE
Allow Preflight 10: sub/sup

### ISSUE THREAD

**Issue by marcioendo** [objectos/objectos#404]
## CSS

```css
/*
Prevent `sub` and `sup` elements from affecting the line height in all browsers.
*/

sub,
sup {
  font-size: 75%;
  line-height: 0;
  position: relative;
  vertical-align: baseline;
}

sub {
  bottom: -0.25em;
}

sup {
  top: -0.5em;
}
```
