### ISSUE TITLE
Allow Preflight 13: button background

### ISSUE THREAD

**Issue by marcioendo** [objectos/objectos#419]
## CSS

```css
/*
1. Correct the inability to style clickable types in iOS and Safari.
2. Remove default button styles.
*/

button,
[type='button'],
[type='reset'],
[type='submit'] {
  -webkit-appearance: button; /* 1 */
  background-color: transparent; /* 2 */
  background-image: none; /* 2 */
}
```
