### ISSUE TITLE
Allow Preflight 14: firefox controls

### ISSUE THREAD

**Issue by marcioendo** [objectos/objectos#420]
## CSS

```css
/*
Use the modern Firefox focus style for all focusable elements.
*/

:-moz-focusring {
  outline: auto;
}

/*
Remove the additional `:invalid` styles in Firefox. (https://github.com/mozilla/gecko-dev/blob/2f9eacd9d3d995c937b4251a5557d95d494c9be1/layout/style/res/forms.css#L728-L737)
*/

:-moz-ui-invalid {
  box-shadow: none;
}
```
