### ISSUE TITLE
Allow Preflight 16: remove margin/padding section

### ISSUE THREAD

**Issue by marcioendo** [objectos/objectos#422]
## CSS

```css
/*
Removes the default spacing and border for appropriate elements.
*/

blockquote,
dl,
dd,
h1,
h2,
h3,
h4,
h5,
h6,
hr,
figure,
p,
pre {
  margin: 0;
}

fieldset {
  margin: 0;
  padding: 0;
}

legend {
  padding: 0;
}

ol,
ul,
menu {
  list-style: none;
  margin: 0;
  padding: 0;
}
```
