### ISSUE TITLE
objectos-css: allow custom properties

### ISSUE THREAD

**Issue by marcioendo** [objectos/objectos#487]
The following:

```java
public class CustomPropertyExample extends CssTemplate {
  public static final ClassSelector SET = ClassSelector.randomClassSelector(5);
  public static final ClassSelector GET = ClassSelector.randomClassSelector(5);
  public static final CustomProperty<ColorValue> THE_COLOR = CustomProperty.names("fw-color");

  protected final void definition() {
    style(
      SET,
      set(THE_COLOR, aqua)
    );

    style(
      GET,
      color(var(THE_COLOR))
    );
  }
}
```

Should render:

```css
.xyz12 {
  --fw-color: aqua;  
}

.ab456 {
  color: var(--fw-color);
}
```
