### ISSUE TITLE
Allow PrettyCssWriter to exclude specified class rule declarations

### ISSUE THREAD

**Issue by marcioendo** [objectos/objectos#57]
This would allow a utility based style sheet such as:

```css
.a { prop: value; }
.b { prop: value; }
.c { prop: value; }
```

Printing with:

```java
PrettyCssWriter.create(
  PrettyCssWriter.exclude(
   Selectors.dot("a"),
   Selectors.dot("b")
  )
);
```

Would generate:

```css
.c {
  prop: value;
}
```
---

## Required tasks

- [x] extract StyleSheetDsl interface
- [x] extract AbstractStyleSheet.ThisX types
- [x] remove Dsl.mark methods
- [x] remove AtMediaElement visit method
- [x] remove RuleElement visit method
- [x] remove MultiDeclarationElement visit method
- [x] introduce StyleEngine interface
- [x] StyleSheetTest
- [x] Merge StyleSheetDslTest + StyleSheetTest
- [x] remove old writer / interpreter / compiler
- [x] replace char[] for String[] in StyleSheetVisitor
- [x] remove Context
- [x] CompiledStyleSheetVisitor needs a proper name

## Test cases

- [x] tc01: result non-empty, filtered out in the middle
- [x] tc02: result will be empty
- [x] tc03: media queries
- [x] tc04: hover state (single)
- [x] tc05: hover state (multiple)
- [x] tc06: empty media query
- [x] tc07: media queries: filter out all media queries, keep only non-query ruleset

**Comment by marcioendo** [comment]
Test case 01:

```java
style(cn("a"), border(zero()));
style(b, zIndex(1));
style(cn("b"), margin(zero()));
style(Css.dot("c"), padding(zero()));

var keep = Set.of("a", "c");
```

**Comment by marcioendo** [comment]
Test case 02:

```java
style(cn("a"), border(zero()));

var keep = Set.of("a", "c");
```

Expected

```css
```

**Comment by marcioendo** [comment]
Test case 03:

```java
style(
  cn("a"),
  zIndex(0)
);

media(
  screen, minWidth(px(800)),

  style(
    cn("b"),
    zIndex(1)
  ),

  style(
    cn("c"),
    zIndex(2)
  )
);


var keep = Set.of("a", "b");
```

Expected

```css
.a {
  z-index: 0;
}

@media screen and (min-width: 800px) {
  .b {
    z-index: 1;
  }
}
```

**Comment by marcioendo** [comment]
Test case 04:

```java
style(
  cn("a"), HOVER,
  zIndex(0)
);

style(
  cn("b"),
  zIndex(1)
);

var keep = Set.of("a", "b");
```

Expected

```css
.a:hover {
  z-index: 0;
}
```

**Comment by marcioendo** [comment]
Test case 05:

```java
style(
  cn("a"), HOVER,
  zIndex(0)
);
style(
  cn("b"), HOVER,
  zIndex(1)
);
style(
  cn("c"),
  zIndex(2)
);

var keep = Set.of("a", "c");
```

Expected

```css
.a:hover {
  z-index: 0;
}
.c {
  z-index: 2;
}
```

**Comment by marcioendo** [comment]
Test case 05 is currently failing.

**Comment by marcioendo** [comment]
Test case 06:

```java
media(
  screen, minWidth(px(800)),

  style(
    cn("a"),
    zIndex(0)
  )
);
media(
  screen, minWidth(px(1024)),

  style(
    cn("b"),
    zIndex(1)
  )
);

var keep = Set.of("b");
```

Expected

```css
@media screen and (min-width: 1024px) {
  .b {
    z-index: 1;
  }
}
```

**Comment by marcioendo** [comment]
Test case 07:

```java
style(
  cn("a"),
  zIndex(0)
);
media(
  screen, minWidth(px(800)),

  style(
    cn("b"),
    zIndex(1)
  )
);
media(
  screen, minWidth(px(1024)),

  style(
    cn("c"),
    zIndex(2)
  )
);

var keep = Set.of("a");
```

Expected

```css
.a {
  z-index: 0;
}
```
